language: node_js
node_js:
    - "11"
install: cd cannabis; npm i;
script: cd cannabis; npm run coverage
after_script: cd cannabis; cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

# language: generic

# sudo: false

# before_install: cd cannabis
# matrix:
#     include:
#         - env: PROJECT=cannabis
#         - env: PROJECT=guitarra

# script: if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $PROJECT; then echo "$PROJECT is being built"; else echo "$PROJECT is NOT being built"; fi

