export * from 'astq'
export { ts } from 'ts-morph'
export { FunctionNames } from './adapter/functionTypes'
export { AttributeNames } from './adapter/attributeTypes'
export * from './astNode'
export { getConfig, setConfig } from './config'
export { getFile, loadProject, setProject } from './file'
export * from './match'
export * from './path'
export { queryAll, queryAllOrThrow, queryAst, queryOne, queryOneOrThrow, QueryResult } from './queryAst'
export { tsMorph }
import * as tsMorph from 'ts-morph'
