export * from 'astq'
export { ts } from 'ts-morph'
export *  from './astNode'
export * from './path'
export { getConfig, setConfig } from './config'
export { loadProject, setProject } from './file'
export *  from './match'
export { Kind } from './nodeKinds'
export { FunctionNames } from './adapter/functionTypes'
export { queryAll, queryAllOrThrow, queryAst, queryOne, queryOneOrThrow, QueryResult } from './queryAst'
export { tsMorph }
import * as tsMorph from 'ts-morph'
